apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: media
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      securityContext:
        runAsUser: 10003
        runAsGroup: 1500
        fsGroup: 1500
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: lidarr
          image: ghcr.io/11notes/lidarr:2.14.5
          ports:
            - containerPort: 8686
          env:
            - name: TZ
              value: "UTC"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /lidarr/etc
            - name: tmp
              mountPath: /tmp
            - name: media
              mountPath: /media
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 1Gi
          startupProbe:
            httpGet: {path: /ping, port: 8686}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet: {path: /ping, port: 8686}
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet: {path: /ping, port: 8686}
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: tmp
          emptyDir: {}
        - name: media
          persistentVolumeClaim:
            claimName: nfs-htpc
        - name: downloads
          persistentVolumeClaim:
            claimName: local-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media
spec:
  selector:
    app: lidarr
  ports:
    - port: 8686
      targetPort: 8686
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  namespace: media
spec:
  rules:
    - host: lidarr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lidarr
                port:
                  number: 8686
  tls:
    - hosts: [lidarr.example.com]
