apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      securityContext:
        runAsUser: 10009
        runAsGroup: 1500
        fsGroup: 1500
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: plex
          image: ghcr.io/11notes/plex:1.42.2
          ports:
            - containerPort: 32400
          env:
            - name: TZ
              value: "UTC"
            # First run only — uncomment, deploy, wait 60s, re-comment, redeploy:
            # - name: PLEX_CLAIM
            #   value: "claim-xxxxxxxxxxxxxxxxxxxx"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /plex/etc
            - name: transcode
              mountPath: /plex/tmp
            - name: media
              mountPath: /media
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
              gpu.intel.com/i915: "1"
            limits:
              memory: 8Gi
              gpu.intel.com/i915: "1"
          startupProbe:
            httpGet: {path: /identity, port: 32400}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet: {path: /identity, port: 32400}
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet: {path: /identity, port: 32400}
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: transcode
          emptyDir:
            sizeLimit: 8Gi
        - name: media
          persistentVolumeClaim:
            claimName: nfs-htpc
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: plex
  ports:
    - port: 32400
      targetPort: 32400
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: media
spec:
  rules:
    - host: plex.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
  tls:
    - hosts: [plex.example.com]
