apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        runAsUser: 10002
        runAsGroup: 1500
        fsGroup: 1500
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: radarr
          image: ghcr.io/11notes/radarr:6.0.4
          ports:
            - containerPort: 7878
          env:
            - name: TZ
              value: "UTC"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /radarr/etc
            - name: tmp
              mountPath: /tmp
            - name: media
              mountPath: /media
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 1Gi
          startupProbe:
            httpGet: {path: /ping, port: 7878}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet: {path: /ping, port: 7878}
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet: {path: /ping, port: 7878}
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: tmp
          emptyDir: {}
        - name: media
          persistentVolumeClaim:
            claimName: nfs-htpc
        - name: downloads
          persistentVolumeClaim:
            claimName: local-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  selector:
    app: radarr
  ports:
    - port: 7878
      targetPort: 7878
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: media
spec:
  rules:
    - host: radarr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 7878
  tls:
    - hosts: [radarr.example.com]
