apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: media
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      securityContext:
        runAsUser: 10006
        runAsGroup: 1500
        fsGroup: 1500
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sabnzbd
          image: ghcr.io/11notes/sabnzbd:4.5.5
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "UTC"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /sabnzbd/etc
            - name: tmp
              mountPath: /tmp
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 1Gi
          startupProbe:
            tcpSocket: {port: 8080}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            tcpSocket: {port: 8080}
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            tcpSocket: {port: 8080}
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sabnzbd-config
        - name: tmp
          emptyDir: {}
        - name: downloads
          persistentVolumeClaim:
            claimName: local-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: media
spec:
  selector:
    app: sabnzbd
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  namespace: media
spec:
  rules:
    - host: sabnzbd.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sabnzbd
                port:
                  number: 8080
  tls:
    - hosts: [sabnzbd.example.com]
