apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 1h
  chart:
    spec:
      chart: immich
      version: ">=0.10.0 <0.11.0"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: v2.5.6
            env:
              TZ: "UTC"
              DB_HOSTNAME: immich-postgresql
              DB_USERNAME: immich
              DB_DATABASE_NAME: immich
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgresql
                    key: postgresql-password

    immich:
      persistence:
        library:
          existingClaim: nfs-immich-photos

    valkey:
      enabled: true

    server:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server
                pullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 200m
                  memory: 512Mi
                  gpu.intel.com/i915: "1"
                limits:
                  memory: 4Gi
                  gpu.intel.com/i915: "1"

    machine-learning:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                tag: v2.5.6-openvino
                pullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 200m
                  memory: 1Gi
                  gpu.intel.com/i915: "1"
                limits:
                  memory: 4Gi
                  gpu.intel.com/i915: "1"
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: emptyDir
