apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: intel-device-plugins-gpu
spec:
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: ">=0.31.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
