apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 1h
  chart:
    spec:
      chart: node-feature-discovery
      version: ">=0.16.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: flux-system
  values:
    worker:
      tolerations:
        - effect: NoSchedule
          operator: Exists
