apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-porkbun
  namespace: cert-manager
spec:
  interval: 1h
  dependsOn:
    - name: cert-manager
  chart:
    spec:
      chart: cert-manager-webhook-porkbun
      version: ">=1.0.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-porkbun
        namespace: flux-system
