apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: you@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          webhook:
            groupName: porkbun.talinx.dev
            solverName: porkbun
            config:
              apiKey:
                key: PORKBUN_API_KEY
                name: porkbun-secret
              secretApiKey:
                key: PORKBUN_SECRET_API_KEY
                name: porkbun-secret
        selector:
          dnsZones:
            - example.com
