---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-media
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/media
  prune: true
  dependsOn:
    - name: infra-controllers
    - name: infra-certs
    - name: infra-storage
    - name: infra-network-policies
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-immich
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/immich
  prune: true
  dependsOn:
    - name: infra-controllers
    - name: infra-certs
    - name: infra-storage
    - name: infra-network-policies
  decryption:
    provider: sops
    secretRef:
      name: sops-age
